{
  "PublicDateAtUSN": "0001-01-01T00:00:00Z",
  "CRD": "0001-01-01T00:00:00Z",
  "Candidate": "CVE-2024-21506",
  "PublicDate": "2024-04-06T05:15:00Z",
  "References": [
    "https://security.snyk.io/vuln/SNYK-PYTHON-PYMONGO-6370597",
    "https://gist.github.com/keltecc/62a7c2bf74a997d0a7b48a0ff3853a03",
    "https://www.cve.org/CVERecord?id=CVE-2024-21506"
  ],
  "Description": "** REJECT ** Duplicate of CVE-2024-5629.",
  "UbuntuDescription": "",
  "Notes": null,
  "Bugs": null,
  "Priority": "medium",
  "DiscoveredBy": "",
  "AssignedTo": "5tev3",
  "Patches": {
    "pymongo": {
      "devel": {
        "Status": "released",
        "Note": ""
      },
      "esm-infra/bionic": {
        "Status": "needed",
        "Note": ""
      },
      "esm-infra/xenial": {
        "Status": "needed",
        "Note": ""
      },
      "focal": {
        "Status": "needed",
        "Note": ""
      },
      "jammy": {
        "Status": "needed",
        "Note": ""
      },
      "mantic": {
        "Status": "needed",
        "Note": ""
      },
      "noble": {
        "Status": "released",
        "Note": ""
      },
      "trusty/esm": {
        "Status": "needed",
        "Note": ""
      },
      "upstream": {
        "Status": "released",
        "Note": "4.7.0"
      }
    }
  },
  "UpstreamLinks": {
    "pymongo": [
      "https://github.com/mongodb/mongo-python-driver/commit/56b6b6dbc267d365d97c037082369dabf37405d2"
    ]
  }
}